### ISSUE TITLE
Pagina de registro

### ISSUE THREAD

**Issue by bmarchete** [MLuiz1992/QR-Security#4]
Achei o layout um pouco infantil. Vocês poderiam trabalhar melhor o contraste das cores e o tamanho das fontes.

Não entendi o porque desta página. Quem vai se registrar nela. Para que eu tenho que me registrar?

**Comment by MLuiz1992** [comment]
Talvez teria mais sentido se somente o administrrador tivesse o direito de registrar alguém

**Comment by maromo71** [comment]
css - mostrar aluno, acertar. Ainda com falhas.

**Comment by MLuiz1992** [comment]
Entendido.
