### ISSUE TITLE
Página inicial

### ISSUE THREAD

**Issue by bmarchete** [MLuiz1992/QR-Security#5]
Apesar de bacana os slides, não vejo funcionalidade nenhuma nesta página. Que tal aproveitá-la melhor com informações importantes, como por exemplo, últimos alunos que passaram o crachá, total de alunos presentes no dia, etc.

**Comment by MLuiz1992** [comment]
Boa ideia! Para o usuário logado podemos mostrar informações desse naipe, enquanto para a index geral, podemos complementar com informações sobre o sistema (O que é QR Security?, equipe, tecnologias utilizadas, etc)

**Comment by maromo71** [comment]
Ainda falta acertar a página index. Podem deixar o slide, mas coloque as informações importantes, como as pedidas pelo binho.

**Comment by MLuiz1992** [comment]
Ok, este será o próximo passo.
