### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by bmarchete** [MLuiz1992/QR-Security#6]
Ainda não entendi o porque de tantas tabelas no banco de dados.  Preciso que vocês expliquem melhor o motivo de separar uma tabela para aluno_dias, outra para salas, outra para saídas, outra para sequências.

Fico aguardando explicações

**Comment by MLuiz1992** [comment]
Precisamos apagar algumas migrations, aluno_dia por exemplo é uma tabela inútil

**Comment by maromo71** [comment]
Ok. Acertado. Arquivo para inicialização bem documentado.
