### ISSUE TITLE
Navegabilidade

### ISSUE THREAD

**Issue by bmarchete** [MLuiz1992/QR-Security#7]
A navegação não está funcionando corretamente.
O login de usuário invade o de admin e vice-versa
A parte de visualizar a frequência do aluno não funcionou no meu teste

Organizar!

**Comment by MLuiz1992** [comment]
Ok, vamos averiguar o caso, na minha máquina funcionou normalmente, porém a desorganização não permite que achemos o porque desse bug.

**Comment by maromo71** [comment]
Ok. Navegação.
